### ISSUE TITLE
HTTPS websites show only blank page

### ISSUE THREAD

**Issue by sasa-b** [kitze/sizzy#26]
Not sure if this is an issue per se but,
I tried my website and a few others which use HTTPS, won't work, because of the X-Frame-Options: DENY header. I mean it won't work with websites that use HTTP as well if they have this header set. Not sure there is a way around it and it reduces the usability of the app unfortunately.

![sizzy](https://cloud.githubusercontent.com/assets/18427949/25557196/011a125a-2d0d-11e7-9385-2ae946e77f9e.png)

**Comment by kitze** [comment]
Hey @sasa-b you're right. If a website chooses not to be embedded, it won't work in the web version of sizzy. 

As you see the error ```Refused to display 'https://sasablagojevic.com/' in a frame because it set 'X-Frame-Options' to 'deny'.```

I'm trying to solve this by making a chrome extension and an electron app.

**Comment by sasa-b** [comment]
Extension would be a real game changer then :)

**Comment by fvsch** [comment]
Hi @kitze. If you’re thinking about making a Chrome Extension, do you think you could look at [WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions)? It’s a spec that’s mostly compatible with Chrome’s extension API and is implemented (to some extent) in Firefox and Edge. I’m not 100% sure Sizzy would work on all three browsers, but it’s worth a look.

**Comment by lvyachao** [comment]
Although this case has been closed, Here is some advices that may solve this problem if needed: Instead of just using iframe to include other url but using PhantomJS or NightmareJS(electron) to downloaded all codes and rendered in a blank iframe. This way can break a lot websites that have X-frame options and leave the space we can deal with more redesign stuff.
